# Generated by Django 3.2.3 on 2021-12-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_volume_catalog_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
